
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import '@/styles/globals.css'
import StyledComponentsRegistry from '../../lib/AntdRegistry'
import MyNavbar from '../../components/Navbar'

import { ConfigProvider, Layout } from 'antd';
import MyFooter from '@/components/Footer'
import theme from '@/theme/themeConfig'
import StoreProvider from '../StoreProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',

}
const roboto = Roboto({ subsets: ['cyrillic'], weight: '400' })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <StyledComponentsRegistry>
          <ConfigProvider
            theme={
              theme
            }>
              
            <StoreProvider>
              < MyNavbar />
              {children}
              <MyFooter />
            </StoreProvider>
          </ConfigProvider>
        </StyledComponentsRegistry>
      </body>
    </html >

  )
}
